### ISSUE TITLE
a couple questions

### ISSUE THREAD

**Issue by bbartling** [google/sbsim#4]
Hello,

This is a really neat project nice job. I have a few a questions.

I am just browsing the .py files inside of `smart_control/simulator` where I notice the sim appears to be a VAV AHU system with hot water reheat which is neat because this is a very common building.

What is the power calculation for mechanical cooling? I couldn't find this in a .py file. A sim for a VAV AHU with DX cooling could be great or air cooled chiller, etc. 

Is the simulation fixed for a set number of zones or VAV boxes? Is the `smart_control/notebooks/SAC_Demo.ipynb` the best example to see how it is all put together?

Thank you!
Ben

**Comment by Jgoldfeder** [comment]
Hi Ben.

1. If I am understanding your question correctly,  we calculate the energy consumption of the AHU here: https://github.com/google/sbsim/blob/copybara_push/smart_control/simulator/air_handler.py#L270

2. No, the number of zones and VAVs is not fixed.

3. Yes, the SAC_Demo.ipynb notebook is the best way to get started. Please let me know if you have any issues getting setup.

Best,
Judah

**Comment by bbartling** [comment]
Super cool project thanks!
